{
  "BOT_TOKEN": "7218020350:AAFX4Ee6kCGV4HPmBM8CvqS9ePFJ7hePUa8",
  "TON_API": "https://tonapi.io/v1",  // כתובת API חינמית להצגת יתרות
  "DEFAULT_WALLET": "UQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}
